#!/usr/bin/env node
/**
 * Article Build Script
 * Bundles article components into a single JSX file.
 *
 * Usage:
 *   node scripts/build-article.js                          # default: market-sizing
 *   node scripts/build-article.js --article ai-memory-architectures
 *
 * Component order matters: Section must come first (defines useInView hook).
 */
const fs = require('fs');
const path = require('path');

// ── Article build configs ───────────────────────────────────────────────────────
const BUILD_CONFIGS = {
  'market-sizing': {
    contentFile: 'article-content.js',
    appFile: 'ArticleApp.jsx',
    outputFile: 'MarketSizingGuide.jsx',
    bundleComment: 'Market Sizing & Beachhead Strategy Guide',
  },
  'ai-memory-architectures': {
    contentFile: 'memory-article-content.js',
    appFile: 'MemoryArticleApp.jsx',
    outputFile: 'AIMemoryArchitectures.jsx',
    bundleComment: 'Building a Company Brain',
  },
};

const args = process.argv.slice(2);
const articleIdx = args.indexOf('--article');
const ARTICLE_SLUG = (articleIdx !== -1 && args[articleIdx + 1]) ? args[articleIdx + 1] : 'market-sizing';

if (!BUILD_CONFIGS[ARTICLE_SLUG]) {
  console.error(`Error: Unknown article "${ARTICLE_SLUG}". Available: ${Object.keys(BUILD_CONFIGS).join(', ')}`);
  process.exit(1);
}

const BCONFIG = BUILD_CONFIGS[ARTICLE_SLUG];
const SRC_DIR = path.resolve(__dirname, '../src');
const DIST_DIR = path.resolve(__dirname, '../dist');
const OUTPUT_FILE = path.join(DIST_DIR, BCONFIG.outputFile);

function readFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`Error: ${filePath} not found.`);
    process.exit(1);
  }
  return fs.readFileSync(filePath, 'utf-8');
}

// Strip ES module imports/exports for inline bundling
function stripModuleSyntax(source) {
  let code = source;
  // Remove import statements (single and multi-line)
  code = code.replace(/^import\s+.*?from\s+['"][^'"]+['"];?\s*$/gm, '');
  code = code.replace(/^import\s*\{[\s\S]*?\}\s*from\s*['"][^'"]+['"];?\s*/gm, '');
  code = code.replace(/^import\s+\w+\s+from\s+['"][^'"]+['"];?\s*$/gm, '');
  // Remove export default
  code = code.replace(/^export default \w+;?\s*$/gm, '');
  // Remove named exports
  code = code.replace(/^export \{[^}]*\};?\s*$/gm, '');
  // Remove export keyword from declarations
  code = code.replace(/^export const /gm, 'const ');
  return code.trim();
}

function build() {
  console.log('Building article bundle...\n');

  // Ensure dist directory exists
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }

  // 1. Article content (generated by parse-article.js)
  console.log(`  Reading ${BCONFIG.contentFile}...`);
  let content = readFile(path.join(SRC_DIR, BCONFIG.contentFile));
  content = stripModuleSyntax(content);

  // 2. Design tokens
  console.log('  Reading design-tokens.js...');
  let tokens = readFile(path.join(SRC_DIR, 'design-tokens.js'));
  tokens = stripModuleSyntax(tokens);

  // 3. Components (order matters: Section first for useInView)
  const components = ['Section', 'RichText', 'Table', 'PullQuote', 'TerminalWindow', 'CardGrid', 'StatsGrid', 'QuadrantChart', 'FlowDiagram', 'Chart'];
  const componentCode = components.map((name) => {
    console.log(`  Reading ${name}.jsx...`);
    const source = readFile(path.join(SRC_DIR, 'components', `${name}.jsx`));
    return stripModuleSyntax(source);
  }).join('\n\n');

  // 4. ArticleApp
  console.log(`  Reading ${BCONFIG.appFile}...`);
  let app = readFile(path.join(SRC_DIR, BCONFIG.appFile));
  app = stripModuleSyntax(app);

  // 5. Assemble bundle
  const bundle = `/**
 * ${BCONFIG.bundleComment} - Single File Bundle
 * Generated: ${new Date().toISOString()}
 *
 * Auto-generated. Do not edit directly.
 */
import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';

// ============================================================================
// ARTICLE CONTENT DATA
// ============================================================================

${content}

// ============================================================================
// DESIGN TOKENS
// ============================================================================

${tokens}

// ============================================================================
// COMPONENTS
// ============================================================================

${componentCode}

// ============================================================================
// ARTICLE APPLICATION
// ============================================================================

${app}

export default App;
`;

  fs.writeFileSync(OUTPUT_FILE, bundle);
  const size = (fs.statSync(OUTPUT_FILE).size / 1024).toFixed(1);
  console.log(`\n✓ Bundle written to ${OUTPUT_FILE}`);
  console.log(`  Size: ${size} KB`);
}

build();
