#!/usr/bin/env node
/**
 * Article Build Script
 * Bundles article components into a single JSX file.
 *
 * Component order matters: Section must come first (defines useInView hook).
 * Output: dist/MarketSizingGuide.jsx
 */
const fs = require('fs');
const path = require('path');

const SRC_DIR = path.resolve(__dirname, '../src');
const DIST_DIR = path.resolve(__dirname, '../dist');
const OUTPUT_FILE = path.join(DIST_DIR, 'MarketSizingGuide.jsx');

function readFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`Error: ${filePath} not found.`);
    process.exit(1);
  }
  return fs.readFileSync(filePath, 'utf-8');
}

// Strip ES module imports/exports for inline bundling
function stripModuleSyntax(source) {
  let code = source;
  // Remove import statements (single and multi-line)
  code = code.replace(/^import\s+.*?from\s+['"][^'"]+['"];?\s*$/gm, '');
  code = code.replace(/^import\s*\{[\s\S]*?\}\s*from\s*['"][^'"]+['"];?\s*/gm, '');
  code = code.replace(/^import\s+\w+\s+from\s+['"][^'"]+['"];?\s*$/gm, '');
  // Remove export default
  code = code.replace(/^export default \w+;?\s*$/gm, '');
  // Remove named exports
  code = code.replace(/^export \{[^}]*\};?\s*$/gm, '');
  // Remove export keyword from declarations
  code = code.replace(/^export const /gm, 'const ');
  return code.trim();
}

function build() {
  console.log('Building article bundle...\n');

  // Ensure dist directory exists
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }

  // 1. Article content (generated by parse-article.js)
  console.log('  Reading article-content.js...');
  let content = readFile(path.join(SRC_DIR, 'article-content.js'));
  content = stripModuleSyntax(content);

  // 2. Design tokens
  console.log('  Reading design-tokens.js...');
  let tokens = readFile(path.join(SRC_DIR, 'design-tokens.js'));
  tokens = stripModuleSyntax(tokens);

  // 3. Components (order matters: Section first for useInView)
  const components = ['Section', 'RichText', 'Table', 'PullQuote', 'TerminalWindow', 'CardGrid', 'StatsGrid'];
  const componentCode = components.map((name) => {
    console.log(`  Reading ${name}.jsx...`);
    const source = readFile(path.join(SRC_DIR, 'components', `${name}.jsx`));
    return stripModuleSyntax(source);
  }).join('\n\n');

  // 4. ArticleApp
  console.log('  Reading ArticleApp.jsx...');
  let app = readFile(path.join(SRC_DIR, 'ArticleApp.jsx'));
  app = stripModuleSyntax(app);

  // 5. Assemble bundle
  const bundle = `/**
 * Market Sizing & Beachhead Strategy Guide - Single File Bundle
 * Generated: ${new Date().toISOString()}
 *
 * Auto-generated. Do not edit directly.
 */
import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';

// ============================================================================
// ARTICLE CONTENT DATA
// ============================================================================

${content}

// ============================================================================
// DESIGN TOKENS
// ============================================================================

${tokens}

// ============================================================================
// COMPONENTS
// ============================================================================

${componentCode}

// ============================================================================
// ARTICLE APPLICATION
// ============================================================================

${app}

export default App;
`;

  fs.writeFileSync(OUTPUT_FILE, bundle);
  const size = (fs.statSync(OUTPUT_FILE).size / 1024).toFixed(1);
  console.log(`\n✓ Bundle written to ${OUTPUT_FILE}`);
  console.log(`  Size: ${size} KB`);
}

build();
